name: Performance Test

on: [ 'pull_request' ]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-plugin-lh:
    name: Build plugin
    uses: ./.github/workflows/build.yml

  performance:
    name: Lighthouse test - WP latest on PHP 7.4
    runs-on: ubuntu-latest
    needs: [build-plugin-lh]
    if: ${{ needs.build-plugin-lh.outputs.changelog_diff }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-plugin-lh.outputs.artifact_name }}
          path: ./elementor

      - name: Setup wp-env
        uses: elementor/elementor-editor-github-actions/actions/setup-wp-env@main
        with:
          php: '7.4'
          active-theme: 'hello-elementor'
          plugins: |-
            ./elementor
          themes: |-
            https://downloads.wordpress.org/theme/hello-elementor.zip
          mappings: |-
            elementor-templates:./tests/playwright/templates

      - name: Import Templates
        uses: elementor/elementor-editor-github-actions/actions/setup-elementor-env@main
        with:
          env: 'testing'
          templates: |-
            elementor-templates

      - name: Run Performance tests
        uses: elementor/elementor-editor-github-actions/actions/run-lighthouse-tests@main
        id: run-lighthouse-tests
        with:
          number-of-runs: 3
          urls: |-
            test:http://localhost:8889/test/
          categories: |-
            performance
